remove shebang cuz it's useless in a bash shell and I'm gonna source it thru network.

diff --git a/signer b/signer
--- a/signer
+++ b/signer
@@ -1,5 +1,3 @@
-#!/usr/bin/env bash
-
 # by 752963e64 - 13/06/2022
 
 function signer.privkey()
@@ -22,8 +20,8 @@ function signer.pubkey()
 
 function signer.sign()
 {
-  [[ ! ${1} ]] && { echo "No digest type provided. Exiting..."; exit 1 }
-  [[ ! -f ${2} ]] && { echo "No file found. Exiting..."; exit 1 }
+  [[ ! ${1} ]] && { echo "No digest type provided. Exiting..."; return 1 }
+  [[ ! -f ${2} ]] && { echo "No file found. Exiting..."; return 1 }
   local dgst=${1}
   local data=${2}
   openssl dgst -${dgst} -sign ~/.signer/privkey.pem -out ${data}.${dgst} ${data}
@@ -34,8 +32,8 @@ function signer.sign()
 
 function signer.verify()
 {
-  [[ ! ${1} ]] && { echo "No digest type provided. Exiting..."; exit 1 }
-  [[ ! -f ${2} ]] && { echo "No file found. Exiting..."; exit 1 }
+  [[ ! ${1} ]] && { echo "No digest type provided. Exiting..."; return 1 }
+  [[ ! -f ${2} ]] && { echo "No file found. Exiting..."; return 1 }
   local dgst=${1}
   local data=${2}
   echo -n "${data} -> "
@@ -45,12 +43,12 @@ function signer.verify()
 function signer.sign.sha1()
 {
   local dgst=${FUNCNAME##*.}
-  signer.sign ${dgst} ${1} || { echo "Critical error occured while signing..."; exit 1 }
+  signer.sign ${dgst} ${1} || { echo "Critical error occured while signing..."; return 1 }
 }
 
 function signer.verify.sha1()
 {
   local dgst=${FUNCNAME##*.}
-  signer.verify ${dgst} ${1} || { echo "Critical error occured while verifying..."; exit 1 }
+  signer.verify ${dgst} ${1} || { echo "Critical error occured while verifying..."; return 1 }
 }
 
